### ISSUE TITLE
Wrong compatibility declaration

### ISSUE THREAD

**Issue by CyrilleB79** [NSoiffer/MathCATForPython#74]
### Issue
The add-on claims to be compatible with NVDA 2019.3 onwards.

Testing with 2023.1, I get the following error at startup:

```
ERROR - globalPluginHandler.listPlugins (09:51:31.598) - MainThread (1496):
Error importing global plugin MathCAT
Traceback (most recent call last):
  File "globalPluginHandler.pyc", line 23, in listPlugins
  File "importlib\__init__.pyc", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\CB232690\AppData\Roaming\nvda\addons\MathCAT\globalPlugins\MathCAT\__init__.py", line 19, in <module>
    from .MathCAT import MathCAT
  File "C:\Users\CB232690\AppData\Roaming\nvda\addons\MathCAT\globalPlugins\MathCAT\MathCAT.py", line 26, in <module>
    from . import libmathcat        # type: ignore
ImportError: DLL load failed: La procédure spécifiée est introuvable.

```

Probably because the .pyd file is a Python 3.11 one, not a 3.7 one.

### Solution
* Either fix the issue with older NVDA version and recheck it with them. For example, add both the .pyd for 3.11 and 3.7 and configure the import path according to Python version
* Or reduce compatibility range

**Comment by NSoiffer** [comment]
Thanks for the report. Someone else already mentioned that to me and the fix will show up in the next release (hopefully this week).

The reason for the incompatibility is, as you surmised, the switch to python 3.11.
